### ISSUE TITLE
TemplateEngines.tryLoadEngines should catch all throwables related to class loading issues

### ISSUE THREAD

**Issue by kwin** [jbake-org/jbake#567]
Currently in https://github.com/jbake-org/jbake/blob/aebf496e326151e91b9403522933c614d12e46a5/jbake-core/src/main/java/org/jbake/template/TemplateEngines.java#L80 only `Exception`s are being caught, but e.g. a `java.lang.NoClassDefFoundError` is not an `Exception` but only derived from a `Throwable`. Since all engines are IMHO optional even a `NoClassDefFoundError` should be caught and logged. For a concrete use cases where this is an issue look at https://github.com/jbake-org/jbake-maven-plugin/pull/17#issuecomment-428534051.

At the same time it would be reasonable to lower the log level to WARN in (https://github.com/jbake-org/jbake/blob/aebf496e326151e91b9403522933c614d12e46a5/jbake-core/src/main/java/org/jbake/template/TemplateEngines.java#L81) as it is perfectly fine if not all template engines are loaded in case they are not actually used.

**Comment by kwin** [comment]
This is a regression caused by https://github.com/jbake-org/jbake/commit/9a0727a6c69bf62d4c9dfb95b59fb0ecc77009bc.

**Comment by jonbullock** [comment]
Yeah I'll merge that in now.
